[package]
name = "blockchain-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
ed25519-dalek = "1.0.1"
rand = "0.7.3"
uuid = { version = "1.4.1", features = ["v4"] }
base58 = "0.2.0"
thiserror = "1.0"
